const CACHE_NAME='carica-kombat-v06515-hall-menu-fix';
self.addEventListener('install',e=>self.skipWaiting());
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('carica-kombat-')&&k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function patchHTML(resp){
 const text=await resp.text();
 const boot=`<style id="ckRankingButtonStyle">#ckRankingGlobalBtn{display:block;width:100%;margin:7px 0;padding:10px 12px;border:1px solid #ff8200;background:linear-gradient(90deg,rgba(255,130,0,.18),rgba(10,12,16,.92));color:white;font-size:14px;font-weight:1000;letter-spacing:.08em;cursor:pointer}#ckAliceHonor{width:100%;margin:14px 0 0;padding:14px 16px;border:1px solid #d6a63a;border-radius:8px;background:linear-gradient(90deg,rgba(214,166,58,.16),rgba(25,20,8,.92));color:#f4d47b;text-align:center;box-sizing:border-box}.ckHallBack{position:absolute;left:50%;bottom:22px;transform:translateX(-50%);z-index:9999;width:min(280px,70vw);padding:12px 18px;border:1px solid #555e69;background:rgba(10,12,16,.94);color:white;font-size:14px;font-weight:1000;letter-spacing:.1em;cursor:pointer}</style><script>(function(){
window.ckHallMenuMode=false;window.ckHallGlobalAlice=null;let autoTimer=null,menuWasOpen=false;
function menuOpen(){const m=document.getElementById('menu');if(!m)return false;const s=getComputedStyle(m);return s.display!=='none'&&s.visibility!=='hidden'&&s.opacity!=='0'&&m.getBoundingClientRect().width>0}
function cancelAuto(){if(autoTimer){clearTimeout(autoTimer);autoTimer=null}}
function setMenuHallVisuals(){const h=document.getElementById('ckHall');if(!h)return;const p=h.querySelector('.panel');if(!p)return;const score=document.getElementById('ckHallScore'),stats=document.getElementById('ckHallStats'),name=document.getElementById('ckHallName'),save=document.getElementById('ckHallSave'),close=document.getElementById('ckHallClose'),list=document.getElementById('ckHallList'),mode=document.getElementById('ckHallMode');p.querySelectorAll(':scope > div').forEach(el=>{if(el!==mode&&el!==stats&&el!==score&&el.textContent.trim()==='TORRE CONCLUÍDA')el.style.display='none'});if(score)score.style.display='none';if(stats)stats.style.display='none';if(name){const q=name.closest('p');if(q)q.style.display='none';else name.style.display='none'}if(save)save.style.display='none';if(close)close.style.display='none';if(mode){mode.style.display='block';mode.textContent='🌎 RANKING GLOBAL'}if(list)list.style.display='block';p.querySelector('h2')?.replaceChildren(document.createTextNode('🌎 RANKING GLOBAL'));let back=document.getElementById('ckHallBack');if(!back){back=document.createElement('button');back.id='ckHallBack';back.className='ckHallBack';back.type='button';back.textContent='↩ VOLTAR';back.onclick=function(){h.classList.remove('on');window.ckHallMenuMode=false;const m=document.getElementById('menu');if(m)m.style.display='grid';menuWasOpen=true;cancelAuto();if(back)back.style.display='none'};h.appendChild(back)}back.style.display='block'}
function restoreTowerVisuals(){const h=document.getElementById('ckHall');if(!h)return;const p=h.querySelector('.panel');if(!p)return;const score=document.getElementById('ckHallScore'),stats=document.getElementById('ckHallStats'),name=document.getElementById('ckHallName'),save=document.getElementById('ckHallSave'),close=document.getElementById('ckHallClose'),mode=document.getElementById('ckHallMode'),list=document.getElementById('ckHallList');if(score)score.style.display='';if(stats)stats.style.display='';if(name){const q=name.closest('p');if(q)q.style.display='';else name.style.display=''}if(save)save.style.display='';if(close)close.style.display='';if(mode)mode.style.display='block';const back=document.getElementById('ckHallBack');if(back)back.style.display='none';const title=p.querySelector('h2');if(title)title.textContent='HALL DA FAMA';p.querySelectorAll(':scope > div').forEach(el=>{if(el.textContent.trim()==='TORRE CONCLUÍDA')el.style.display=''});}
async function loadMenuGlobal(){if(typeof CK_SUPABASE_URL==='undefined'||typeof CK_SUPABASE_KEY==='undefined')return;try{const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),4500);const r=await fetch(CK_SUPABASE_URL+'/rest/v1/hall_da_fama?select=id,nome,personagem,score,perfects,caricalities,continues,criado_em&order=score.desc&limit=100',{headers:{apikey:CK_SUPABASE_KEY},signal:ctl.signal});clearTimeout(tm);if(!r.ok)throw Error('HTTP '+r.status);const raw=await r.json(),best=new Map();for(const x of Array.isArray(raw)?raw:[]){const n=String(x?.nome||'').trim().toUpperCase();if(!n||n==='MRC')continue;const old=best.get(n);if(!old||(Number(x.score)||0)>(Number(old.score)||0))best.set(n,x)}const all=[...best.values()].sort((a,b)=>(Number(b.score)||0)-(Number(a.score)||0));const ai=all.findIndex(x=>String(x?.nome||'').trim().toUpperCase()==='ALICE HELENA');window.ckHallGlobalAlice=ai>=10?all[ai]:null;const rows=all.slice(0,10);const ol=document.getElementById('ckHallList');if(ol)ol.innerHTML=rows.length?rows.map((x,i)=>'<li>'+(i+1)+'º &nbsp; '+String(x.nome||'PLAYER').replace(/[&<>]/g,'')+' — '+String(Number(x.score)||0).padStart(6,'0')+'</li>').join(''):'<li>SEJA O PRIMEIRO!</li>';paintAlice();}catch(e){console.warn('Ranking global:',e)}}
function paintAlice(){let el=document.getElementById('ckAliceHonor'),h=document.getElementById('ckHall');if(!h)return;if(!el){el=document.createElement('div');el.id='ckAliceHonor';h.querySelector('.panel')?.appendChild(el)}const a=window.ckHallGlobalAlice;if(window.ckHallMenuMode&&a){el.style.display='block';el.innerHTML='<div>🏆 MENÇÃO DOURADA • PRIMEIRA CAMPEÃ</div><div>ALICE HELENA</div><div>'+(Number(a.score)||0).toString().padStart(6,'0')+' PONTOS</div>'}else el.style.display='none'}
function openMenuHall(){window.ckHallMenuMode=true;cancelAuto();if(typeof ckOpenHall==='function')ckOpenHall();setTimeout(()=>{setMenuHallVisuals();loadMenuGlobal();},60)}
function watch(){const open=menuOpen();if(open&&!menuWasOpen){menuWasOpen=true;window.ckHallMenuMode=false;autoTimer=setTimeout(()=>{if(menuOpen())openMenuHall()},6000)}if(!open){menuWasOpen=false;cancelAuto()}if(window.ckHallMenuMode){setMenuHallVisuals()}else{restoreTowerVisuals()}const b=document.getElementById('ckRankingGlobalBtn');if(!b){const box=document.querySelector('#menu .menuBox')||document.querySelector('.menuBox');if(box){const x=document.createElement('button');x.id='ckRankingGlobalBtn';x.type='button';x.textContent='🌎 RANKING GLOBAL';x.onclick=openMenuHall;const note=box.querySelector('.note');note?box.insertBefore(x,note):box.appendChild(x)}}paintAlice()}
document.addEventListener('pointerdown',()=>{if(autoTimer&&menuOpen())cancelAuto()},true);document.addEventListener('touchstart',()=>{if(autoTimer&&menuOpen())cancelAuto()},{capture:true,passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{watch();setInterval(watch,250)});else{watch();setInterval(watch,250)}
})();</script>`;
 return new Response(text.replace('</head>',boot+'</head>'),{status:resp.status,statusText:resp.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}});
}
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const u=new URL(e.request.url),html=e.request.mode==='navigate'||u.pathname.endsWith('/')||u.pathname.endsWith('/index.html');if(html){e.respondWith(fetch(e.request,{cache:'no-store'}).then(patchHTML).catch(()=>caches.match(e.request)));return}e.respondWith(caches.match(e.request).then(hit=>hit||fetch(e.request).then(r=>{const c=r.clone();caches.open(CACHE_NAME).then(x=>x.put(e.request,c)).catch(()=>{});return r})))})
